"""added goal model

Revision ID: 986d7fc91229
Revises: c5c1e5da8e8d
Create Date: 2024-11-07 12:16:09.790107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986d7fc91229'
down_revision = 'c5c1e5da8e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
